## Answers for week 7

* Name: Wendy Oosterhof
* Username: wroosterhof
* Student s-number: S6328091
* Group: AS6

In [32]:
#7.1 SESSION QUIZ
import numpy as np
from numpy import linalg as la

A = np.array([1,2,3, 0,-4,1, 0,3,-1]).reshape(3,3)
print(f"Matrix A: \n{A}")


print(f"The determinant of A is:{la.det(A)}")

b = np.array([2,2,1])
x,y,z = la.solve(A, b)
print(f" A = \n{A}")
print(f" b = {b}" )
print(f"The solution (x,y,z) for Ax = b: ({x},{y},{z}).")


print("A is orthogonal if A@A.T = I")
Atrans = A.T
print(f"The transposed matrix of A is: \n{Atrans}")
print(f"The identity matrix: {np.identity(3)}")
print(f"A@A.T == I: \n{A@A.T == np.identity(3)}")
print(f"The dot product of A and A transposed is not the same as the identity matrix, so no, A is not orthogonal.")

Lambda, v = la.eig(A)
print(f"The Eigenvalues are: {Lambda}.")

Matrix A: 
[[ 1  2  3]
 [ 0 -4  1]
 [ 0  3 -1]]
The determinant of A is:1.0
 A = 
[[ 1  2  3]
 [ 0 -4  1]
 [ 0  3 -1]]
 b = [2 2 1]
The solution (x,y,z) for Ax = b: (38.0,-3.0,-10.0).
A is orthogonal if A@A.T = I
The transposed matrix of A is: 
[[ 1  0  0]
 [ 2 -4  3]
 [ 3  1 -1]]
The identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A@A.T == I: 
[[False False False]
 [False False False]
 [False False False]]
The dot product of A and A transposed is not the same as the identity matrix, so no, A is not orthogonal.
The lambda is: [ 1.         -4.79128785 -0.20871215].
The Eigenvalues are: [ 1.         -4.79128785 -0.20871215].


In [43]:
#7.2 OPTIONAL
from math import radians, cos, sin
def Ex(angle):
    a = cos(radians(angle))
    b = sin(radians(angle))
    Ex = np.array([1,0,0, 0,a,b, 0,-b,a]).reshape(3,3)
    return Ex

def Ey(angle):
    a = cos(radians(angle))
    b = sin(radians(angle))
    Ey = np.array([a,0,-b, 0,1,0, b,0,a]).reshape(3,3)
    return Ey
def Ez(angle):
    a = cos(radians(angle))
    b = sin(radians(angle))
    Ez = np.array([a,b,0, -b,a,0, 0,0,1]).reshape(3,3)
    return Ez


print(f"\nEx(33)=\n{Ex(33)}")
print(f"\nEy(33)=\n{Ey(33)}")
print(f"\nEz(33)=\n{Ez(33)}")


Ex(33)=
[[ 1.          0.          0.        ]
 [ 0.          0.83867057  0.54463904]
 [ 0.         -0.54463904  0.83867057]]

Ey(33)=
[[ 0.83867057  0.         -0.54463904]
 [ 0.          1.          0.        ]
 [ 0.54463904  0.          0.83867057]]

Ez(33)=
[[ 0.83867057  0.54463904  0.        ]
 [-0.54463904  0.83867057  0.        ]
 [ 0.          0.          1.        ]]


In [85]:
#7.3 SESSION QUIZ

E = Ez(180-123)@Ey(90-27.4)@Ez(192.25)
print(E)

print("For E to be a rotational matrix we need E.T = inv.(E) and det(E) = 1")
print(f"\nThe transposed matrix is: \n{E.T}")
print(f"The inverse of the matrix is: \n{la.inv(E)}")
print(f"E.T == E^-1: {np.allclose(E.T, la.inv(E))}")

print(f"\nThe determinant of E is: {la.det(E)}.")
print(f"Det(E) == 1: {la.det(E) == 1}.")

print(f"\nBoth the conditions are met so E is proven to be a rotational matrix.")

#Eigenvalues
Lambda, v = la.eig(E)
print(f"\nThe eigenvalues: {Lambda}.")
print(f"So there is an eigenvector that is close to one: {Lambda[2]}.")

dec = radians(27.4)
RA = radians(192.25)
r = np.array([cos(dec)*cos(RA), cos(dec)*sin(RA), sin(dec)])
print(f"\nFrom the given equation for r: r = {r}, which are inline with the given vectors.")
print(f"The norm of these vectors is: {la.norm(r)}.")

v2 = E@r
print(f"\nThe vector v2 is not exactly (0,0,1) but is very close to is with its values being: {v2}.")


[[-0.06698874 -0.87275577 -0.48353891]
 [ 0.49272847 -0.45034696  0.74458463]
 [-0.86760081 -0.1883746   0.46019978]]
For E to be a rotational matrix we need E.T = inv.(E) and det(E) = 1

The transposed matrix is: 
[[-0.06698874  0.49272847 -0.86760081]
 [-0.87275577 -0.45034696 -0.1883746 ]
 [-0.48353891  0.74458463  0.46019978]]
The inverse of the matrix is: 
[[-0.06698874  0.49272847 -0.86760081]
 [-0.87275577 -0.45034696 -0.1883746 ]
 [-0.48353891  0.74458463  0.46019978]]
E.T == E^-1: True

The determinant of E is: 1.0.
Det(E) == 1: True.

Both the conditions are met so E is proven to be a rotational matrix.

The eigenvalues: [-0.52856796+0.84889099j -0.52856796-0.84889099j  1.        +0.j        ].
So there is an eigenvector that is close to one: (0.9999999999999999+0j).

From the given equation for r: r = [-0.86760081 -0.1883746   0.46019978], which are inline with the given vectors.
The norm of these vectors is: 1.0.

The vector v2 is not exactly (0,0,1) but is very close to is

In [105]:
#7.4

#Data:
x = np.array([1.2, 2.0, 3.1, 4.4, 4.9, 5.8, 6.9, 8.0, 9.1, 9.9])
y = np.array([0.3, 0.5, 0.7, 0.8, 1.3, 1.6, 2.0, 2.3, 2.9, 3.0])

#X = float(input("Which value for x?"))
X = 2.5

smallerx = []
biggerx = []
smallery = []
biggery = []
for i in range(len(x)):
    if x[i] < X:
        smallerx.append(x[i])
        smallery.append(y[i])
    elif x[i] > X:
        biggerx.append(x[i])
        biggery.append(y[i])
    else:
        print(f"The x given has the y value of {y[i]}.")

print(smallerx)
x1 = smallerx[-1]
y1 = smallery[-1]
x2 = biggerx[0]
y2 = biggery[0]

Y = y1 + ((y2-y1)(X-x1))/(x2-x1)
print(Y)

[np.float64(1.2), np.float64(2.0)]


TypeError: 'numpy.float64' object is not callable